/*
 * 7SEGMENT_Configuration.h
 *
 *  Created on: Oct 23, 2019
 *      Author: AVE-LAP-070
 */

#ifndef HAL_HAL_INCLUDES_7SEGMENT_INCLUDES_7SEGMENT_CONFIGURATION_H_
#define HAL_HAL_INCLUDES_7SEGMENT_INCLUDES_7SEGMENT_CONFIGURATION_H_



#define NUMBER_OF_7SEGMENT   2

#define NUMBER_OF_PINS       4




uint8 arrOfPins[NUMBER_OF_7SEGMENT][NUMBER_OF_PINS] = {{BIT0,BIT1,BIT2,BIT3},{BIT0,BIT1,BIT2,BIT3}};

uint8 arrOfPinsPorts[NUMBER_OF_7SEGMENT][NUMBER_OF_PINS] = {{PORTB,PORTB,PORTB,PORTB},{PORTB,PORTB,PORTB,PORTB}};

uint8 arrOfEnablePorts[NUMBER_OF_7SEGMENT] = {PORTD,PORTD};

uint8 arrOfEnablePins[NUMBER_OF_7SEGMENT]  = {BIT2,BIT3};



#endif /* HAL_HAL_INCLUDES_7SEGMENT_INCLUDES_7SEGMENT_CONFIGURATION_H_ */
