/*
 * LED_Configuration.h
 *
 *  Created on: Oct 22, 2019
 *      Author: AVE-LAP-070
 */

#ifndef HAL_HAL_INCLUDES_LED_INCLUDES_LED_CONFIGURATION_H_
#define HAL_HAL_INCLUDES_LED_INCLUDES_LED_CONFIGURATION_H_


#define NUMBER_OF_LEDS   4

uint8 LEDS_BITS[NUMBER_OF_LEDS]  =   {BIT4,BIT5,BIT6,BIT7};
uint8 LEDS_PORTS[NUMBER_OF_LEDS] =  {PORTB,PORTB,PORTB,PORTB};
uint8 LEDS_VALUES[NUMBER_OF_LEDS]= {LED_OFF,LED_OFF,LED_OFF,LED_OFF};


#endif /* HAL_HAL_INCLUDES_LED_INCLUDES_LED_CONFIGURATION_H_ */
