/*
 * LED_Private.h
 *
 *  Created on: Oct 22, 2019
 *      Author: AVE-LAP-070
 */

#ifndef HAL_HAL_INCLUDES_LED_INCLUDES_LED_PRIVATE_H_
#define HAL_HAL_INCLUDES_LED_INCLUDES_LED_PRIVATE_H_



#endif /* HAL_HAL_INCLUDES_LED_INCLUDES_LED_PRIVATE_H_ */
